# export IS_LOCAL=True
# docker run -d -p 4444:4444 --name selenium-hub selenium/hub:3.141.59                                                         
# docker run -d --link selenium-hub:hub selenium/node-chrome:3.141.59
# docker run -d --link selenium-hub:hub selenium/node-firefox:3.141.59

version: "3.7"
services:
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "4444:4444"
  
  node-chrome:
    image: selenium/node-chrome:3.141.59
    container_name: node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  
  node-firefox:
    image: selenium/node-firefox:3.141.59
    container_name: node-firefox
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444